### ISSUE TITLE
doesnt work for me

### ISSUE THREAD

**Issue by jameel-shorosh-silk** [shainisan/real-life-chess-vision#2]
Hi,
I am trying to run it again and again on multiple chess board pictures, and it never worked. I am wondering what wrong I am doing?

this is the error I am getting:

File <__array_function__ internals>:180, in argmin(*args, **kwargs)

File c:\Users\jameel.shorosh\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\fromnumeric.py:1312, in argmin(a, axis, out, keepdims)
   1225 """
...
     64     # Call _wrapit fro
m within the except clause to ensure a potential
     65     # exception has a traceback chain.
     66     return _wrapit(obj, method, *args, **kwds)

ValueError: attempt to get argmin of an empty sequence

![chess_picture](https://github.com/shainisan/real-life-chess-vision/assets/109660429/1ad28d4d-84a8-4496-8ab4-f21cef9d4dca)

**Comment by shainisan** [comment]
You have to train it first on your chess set. It is trained on mine...

**Comment by jameel-shorosh-silk** [comment]
Thanks for your fast response! can you please send the instructions how to train it on my chess board?

**Comment by shainisan** [comment]
I can recommend this fantastic article: https://blog.roboflow.com/how-to-train-yolov8-on-a-custom-dataset/
